version: '3'
services:
  postgres:
    container_name: shieldpay
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shieldpay
      